version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - 'curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -'
      - 'export PATH=$PATH:$HOME/.poetry/bin'
      - 'poetry config virtualenvs.create false'
      - 'poetry install'
  build:
    commands:
      - make test
      - make package
artifacts:
  files:
    - 'build/artifacts/*.zip'
    - 'build/artifacts/*.txt'
  discard-paths: yes