Transform: AWS::Serverless-2016-10-31

Resources:
  TelescopeMSK:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../../src
      FunctionName: telescope-msk
      Handler: handler.lambda_handler
      Role: TelescopeMSKRole
      Runtime: python3.9
